#pragma once
// Default
#include <windows.h>
#include <iostream>
#include <array>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <tchar.h>
#include <string>
#include <wrl/client.h>
#include <cstdint>
#include <vector>
#include <cmath>
#include <algorithm>
#include <fstream>
#include <cmath>
#include <chrono>
// Utils
#include "Engine/Keyboard.h"
#include "Engine/Size.h"
#include "Engine/Vector2.h"
#include "Engine/Vector3.h"
#include "Engine/Rect.h"
#include "Engine/Colors.h"
#include "Engine/Vertex.h"
#include "Engine/Timer.h"
#include "Engine/Graphics.h"
#include "Engine/Window.h"
#include "Engine/Texture2D.h"